const items = [
  {
    id: "01",
    img: "img1.jpg",
    company: "Puma",
    item_name: " Cotton Logo Outdoor Tank",
    original_price: 1099,
    current_price: 439,
    discount_percent: 60,
    return_period: 14,
    delivery_date: "04 june 2024",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
  },
  {
    id: "02",
    img: "img2.jpg",
    company: "Lewis",
    item_name: "Printed Pure Cotton T-Shirt",
    original_price: 1099,
    current_price: 439,
    discount_percent: 60,
    return_period: 14,
    delivery_date: "04 june 2024",
    rating: {
      stars: 4.3,
      noOfReviews: 1200,
    },
  },
  {
    id: "03",
    img: "img3.jpg",
    company: "Libas",
    item_name: "Women Sea Green Floral Printed Kurta with Palazzos & Dupatta",
    original_price: 2799,
    current_price: 1203,
    discount_percent: 57,
    return_period: 14,
    delivery_date: "04 june 2024",
    rating: {
      stars: 4.3,
      noOfReviews: 10000,
    },
  },
  {
    id: "04",
    img: "img4.avif",
    company: "Libas",
    item_name: "Ethnic Motifs Printed Kurti",
    original_price: 1299,
    current_price: 324,
    discount_percent: 75,
    return_period: 14,
    delivery_date: "04 june 2024",
    rating: {
      stars: 4.4,
      noOfReviews: 800,
    },
  },
  {
    id: "05",
    img: "img5.jpg",
    company: "Zaveri Pearls",
    item_name: "Set of 2 Drop Earrings",
    original_price: 1995,
    current_price: 319,
    discount_percent: 84,
    return_period: 14,
    delivery_date: "04 june 2024",
    rating: {
      stars: 4.3,
      noOfReviews: 845,
    },
  },
  {
    id: "06",
    img: "img6.avif",
    company: "U.S. Polo Assn.",
    item_name: "Men Clarin Sneakers",
    original_price: 2999,
    current_price: 1349,
    discount_percent: 55,
    return_period: 14,
    delivery_date: "04 june 2024",
    rating: {
      stars: 4.2,
      noOfReviews: "41.1k",
    },
  },
  {
    id: "07",
    img: "img7.jpg",
    company: "Apple",
    item_name: "Watch Series 9 GPS",
    original_price: 41900,
    current_price: 37710,
    discount_percent: 10,
    return_period: 14,
    delivery_date: "04 june 2024",
    rating: {
      stars: 4,
      noOfReviews: 845,
    },
  },
  {
    id: "08",
    img: "img8.jpg",
    company: "Tommy Hilfiger",
    item_name: "15 inch Laptop Overnighter 45L",
    original_price: 10999,
    current_price: 2799,
    discount_percent: 35,
    return_period: 14,
    delivery_date: "04 june 2024",
    rating: {
      stars: 4.4,
      noOfReviews: 5400,
    },
  },
];
